const  ActionTypes = {
    SET_CARD_LIST: "SET_CARD_LIST",
    CLEAR_CARD_LIST: "CLEAR_CARD_LIST",
    SET_SELECTED_SLOT: "SET_SELECTED_SLOT",
    SET_ROW_BINGO: "SET_ROW_BINGO",
    SET_COLUMN_BINGO: "SET_ROW_BINGO",
    SET_DIAGONAL_BINGO: "SET_ROW_BINGO"

};

export default ActionTypes;
