
export const ROW = 5;
export const COLUMN = 5;

export const CONF_SLOT_LABELS = [
    "Noise in the background",
    "Hello...hello?",
    "I need to jump to another call",
    "Can every go on mute",
    "Could you please get closer to mic",
    "(Loud painful echo/feedback)",
    "Next slide please",
    "Having Internet issues",
    "Can we take take this offline",
    "Has everyone joined?",
    "Could you please share these slides afterwards",
    "Is _____ joining?",
    "Why is eveyone silent?",
    "Can somebody grant presenter rights to me?",
    "Can you see my screen?",
    "Sorry ,something wrong with my calender",
    "Could you please repeat yourself?",
    "let's wait for Dwite to join",
    "Sorry ,i was speaking with my mic on mute.",
    "Sorry, I wasn't able to find the conference id",
    "Next slide please",
    "Can you mail that to all the participants?",
    "I will start recording of the meeting",
    "(Talking to someone with mic unmuted)"
];

export const SLOT_LABELS = [
    "Kelly’s eye",
    "Up to tricks",
    "One little duck",
    "Four and seven",
    "Cup of tea",
    "Four dozen",
    "Knock at the door",
    "PC",
    "Man alive",
    "Half a century",
    "Tom Mix/Half a dozen",
    "Tweak of the thumb",
    "Lucky seven",
    "Danny La Rue",
    "Garden gate",
    "Here comes Herbie/Stuck in a tree",
    "Doctor’s orders",
    "Clean the floor",
    "Biden’s den",
    "Snakes alive",
    "Legs eleven",
    "Shotts Bus",
    "One dozen",
    "Heinz varieties",
    "Unlucky for some",
    "Make them wait",
    "Valentine’s Day",
    "Brighton Line",
    "Young and keen",
    "Five dozen",
    "Sweet 16 and never been kissed",
    "Baker’s bun",
    "Dancing queen",
    "Turn the screw/Tickety-boo",
    "Coming of age",
    "Tickle me 63",
    "Goodbye teens",
    "Red raw",
    "One score",
    "Old age pension",
    "Royal salute/Key of the door",
    "Clickety click",
    "Two little ducks",
    "Stairway to heaven",
    "Thee and me",
    "Saving Grace",
    "Two dozen",
    "Favourite of mine",
    "Duck and dive",
    "Three score and ten",
    "Pick and mix",
    "Bang on the drum",
    "Gateway to heaven",
    "Six dozen",
    "In a state/Over weight",
    "Queen bee",
    "Rise and shine",
    "Hit the floor",
    "Dirty Gertie",
    "Strive and strive",
    "Get up and run",
    "Trombones",
    "Buckle my shoe",
    "Sunset strip",
    "Dirty knee/All the threes/Fish, chips & peas",
    "39 more steps",
    "Ask for more",
    "One more time",
    "Jump and jive",
    "Eight and blank",
    "Three dozen",
    "Stop and run",
    "More than eleven",
    "Straight on through",
    "Christmas cake",
    "Time for tea",
    "39 steps",
    "Seven dozen",
    "Life begins",
    "Staying alive",
    "Time for fun",
    "Between the sticks",
    "Winnie the Pooh",
    "Torquay in Devon",
    "Down on your knees",
    "Two fat ladies",
    "Droopy drawers",
    "Nearly there",
    "Halfway there",
    "Top of the shop",
]

export const FREE_SLOT = "DON'T MIND ME, IT'S FREE";
